#!/usr/bin/env bash

die() {
    case "$1" in
        i) printf 'INFO: %s\n' "$2" >&2 ;;
        e) printf 'ERROR: %s\n' "$2" >&2 ;;
        w) printf 'WARNING: %s\n' "$2" >&2 ;;
        f) printf 'FATAL: %s\n' "$2" >&2 ;;
        *) printf 'ERROR: Invalid option or format\n' >&2 ;;
    esac
}

# Check pre-requisites
[[ ${BASH_VERSINFO[0]} -gt 3 ]] || {
    die f "Bash version 4 or newer is required. Current version: $BASH_VERSION"
    exit 1
}

jq --version >/dev/null 2>&1 || {
    die f "jq is required. Please install it, then try again."
    exit 1
}

if [[ $(chezmoi data | jq --raw-output '.chezmoi.os') == "windows" ]]; then
    die f "Windows is not supported yet."
    exit 1
fi

NAME="$(basename "$0")"
CHEZMOISOURCE="$(chezmoi source-path)"

# Determine editor: environment variable, chezmoi.toml, or vi
[[ $EDITOR ]] || {
    EDITOR="$(chezmoi dump-config | jq --raw-output '.edit.command')"
    EDITOR="${EDITOR:-vi}"
}

change_dir() {
    cd "$1" || {
        die f "Failed to change $1"
        exit 1
    }
}

help() {
    cat <<HERE
Manage template files in $CHEZMOISOURCE/.chezmoitemplates
Use $NAME <subcommand> -h to get help for individual subcommands.

Usage: $NAME [options] {add|remove} [options] source targets

Options:
  -h		Show this help message and exit.

Subcommands:
  add		Create a source template file and target templates pointing to it.
  remove	Placeholder
  rename	Placeholder

Parameters:
  source	The source template config file relative to $CHEZMOISOURCE/.chezmoitemplates
  targets	Colon separated list of paths relative to $CHEZMOISOURCE.
  		These are the files that will point to the source template.
HERE
}

set_CONSTANTS() {
    if [[ $1 == /* ]]; then
        die e "File path must be relative to $PREFIX"
        exit 1
    fi
    ORIGINAL_PARENT="${1%/*}" ORIGINAL_PARENT="${ORIGINAL_PARENT%"$1"}"
    TEMPLATE_STR="{{ template \"$PREFIX/$1\" . }}"
    FILENAME="$(basename "$1")"
    TRANSFORMED_PARENT="${ORIGINAL_PARENT:+"$(sed -E 's|([^/]+)|exact_\1|g' <<<"$ORIGINAL_PARENT")"}"
}

# System specific templates, pointing to the source template
process_system_templates() {
    local target_dir="$CHEZMOISOURCE/${TARGETPREFIX[$1]:-$FILENAME}"
    [[ -n $TRANSFORMED_PARENT ]] && target_dir="$CHEZMOISOURCE/${TARGETPREFIX[$1]}/$TRANSFORMED_PARENT"
    [[ -d $target_dir ]] || mkdir -p "$target_dir"
    echo "$TEMPLATE_STR" >"$target_dir/$FILENAME.tmpl"
}

tmpl::add() {
    local OPTIND opt prefix

}

tmpl::remove() {
    :
}

parse_subcommands() {
    local subcmd="$1"
    shift
    case "$subcmd" in
        add) tmpl::add "$@" ;;
        remove) tmpl::remove "$@" ;;
        *)
            die e "Unknown subcommand or option"
            exit 1
            ;;
    esac
}

main() {
    local opt OPTIND OPTARG
    while getopts h opt "$@"; do
        case "$opt" in
            h)
                help
                exit
                ;;
            ?)
                die e 'Unknown option.'
                usage >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    parse_subcommands "$@"
}

# Entry point
main "$@"
